package com.ai.modules.review.vo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;


@Data
@ApiModel(value="DWB_ADMMISION对象", description="入院记录")
public class DwbAdmmisionVo {

	@ApiModelProperty(value = "住院唯一标识")
	private String bid;
	@ApiModelProperty(value = "院区名称")
	private String aera;
	@ApiModelProperty(value = "科室名称")
	private String deptname;
	@ApiModelProperty(value = "病房号")
	private String roomNo;
	@ApiModelProperty(value = "病床号")
	private String bedno;
	@ApiModelProperty(value = "患者姓名")
	private String clientname;
	@ApiModelProperty(value = "性别代码")
	private String sexCode;
	@ApiModelProperty(value = "出生日期")
	private String birthday;
	@ApiModelProperty(value = "年龄（岁）")
	private Double yearage;
	@ApiModelProperty(value = "年龄（月）")
	private Double monthage;
	@ApiModelProperty(value = "民族代码")
	private String nationcode;
	@ApiModelProperty(value = "民族名称")
	private String nation;
	@ApiModelProperty(value = "婚姻状况")
	private String marriagestatus;
	@ApiModelProperty(value = "地址-省(自治区、直辖市)")
	private String addrprovince;
	@ApiModelProperty(value = "地址-市（地区、州）")
	private String addrcity;
	@ApiModelProperty(value = "地址-县（区）")
	private String addrcounty;
	@ApiModelProperty(value = "地址-乡（镇、街道办事处）")
	private String addrtown;
	@ApiModelProperty(value = "地址-村（街、路、弄等）")
	private String addrvillage;
	@ApiModelProperty(value = "地址-门牌号码")
	private String address;
	@ApiModelProperty(value = "职业类别代码")
	private String professiontype;
	@ApiModelProperty(value = "入院日期时间")
	private String admitdate;
	@ApiModelProperty(value = "陈述者与患者的关系代码")
	private String expressorrelation;
	@ApiModelProperty(value = "陈述内容是否可靠")
	private String isExpressCredible;
	@ApiModelProperty(value = "主诉")
	private String complain;
	@ApiModelProperty(value = "现病史")
	private String diseaseprocedure;
	@ApiModelProperty(value = "患者既往是否健康")
	private String healthStatus;
	@ApiModelProperty(value = "疾病史（含外伤史）")
	private String diseasehistory;
	@ApiModelProperty(value = "患者传染性标志")
	private String contagionSign;
	@ApiModelProperty(value = "传染病史")
	private String contagionHis;
	@ApiModelProperty(value = "预防接种史")
	private String vaccinateHis;
	@ApiModelProperty(value = "手术史")
	private String surgeryHis;
	@ApiModelProperty(value = "输血史")
	private String bloodTransHis;
	@ApiModelProperty(value = "过敏史")
	private String allergyHis;
	@ApiModelProperty(value = "个人使")
	private String porsonHis;
	@ApiModelProperty(value = "婚育史")
	private String birthHis;
	@ApiModelProperty(value = "月经史")
	private String menstruationHis;
	@ApiModelProperty(value = "家族史")
	private String familyHis;
	@ApiModelProperty(value = "体温（°c）")
	private Double bodyTemprature;
	@ApiModelProperty(value = "脉率（次/min）")
	private String pulserate;
	@ApiModelProperty(value = "呼吸频率（次/min）")
	private String respirefeq;
	@ApiModelProperty(value = "收缩压（mmhg）")
	private String systolicPressure;
	@ApiModelProperty(value = "舒张压（mmhg）")
	private String diastolicPressure;
	@ApiModelProperty(value = "身高（cm）")
	private String height;
	@ApiModelProperty(value = "体重（kg）")
	private String weight;
	@ApiModelProperty(value = "一般状况检查结果")
	private String generalCheck;
	@ApiModelProperty(value = "皮肤和黏膜检查结果")
	private String skinCheck;
	@ApiModelProperty(value = "全身浅表淋巴结检查结果")
	private String lymphCheck;
	@ApiModelProperty(value = "头部及其器官检查结果")
	private String headCheck;
	@ApiModelProperty(value = "颈部检查结果")
	private String neckCheck;
	@ApiModelProperty(value = "胸部检查结果")
	private String chestCheck;
	@ApiModelProperty(value = "腹部检查结果")
	private String abdomenCheck;
	@ApiModelProperty(value = "肛门指诊检查结果")
	private String anusCheck;
	@ApiModelProperty(value = "外生殖器检查结果")
	private String genitalCheck;
	@ApiModelProperty(value = "脊柱检查结果")
	private String spineCheck;
	@ApiModelProperty(value = "四肢检查结果")
	private String limbCheck;
	@ApiModelProperty(value = "神经系统检查结果")
	private String nervCheck;
	@ApiModelProperty(value = "专科情况")
	private String specialCheck;
	@ApiModelProperty(value = "辅助检查结果")
	private String assistCheck;
	@ApiModelProperty(value = "中医“四诊”观察结果")
	private String chimedicalDiag;
	@ApiModelProperty(value = "治则治法")
	private String chimedicalTreatway;
	@ApiModelProperty(value = "接诊医师")
	private String admitDoctor;
	@ApiModelProperty(value = "住院医师")
	private String residentDoctor;
	@ApiModelProperty(value = "主治医师")
	private String doctorname;
	@ApiModelProperty(value = "主任医师")
	private String directordoctor;
	@ApiModelProperty(value = "状态")
	private String status;
	@ApiModelProperty(value = "患者传染性标志名称")
	private String contagionSignname;
	@ApiModelProperty(value = "就诊id")
	private String visitid;
	@ApiModelProperty(value = "病案号")
	private String caseId;
	@ApiModelProperty(value = "职业名称")
	private String profession;
	@ApiModelProperty(value = "etl数据来源")
	private String etlSource;
	@ApiModelProperty(value = "etl时间")
	private String etlTime;
	@ApiModelProperty(value = "项目")
	private String project;
	@ApiModelProperty(value = "项目data")
	private String projectData;

}
