package org.jeecg.test;

import com.alibaba.fastjson.JSONObject;

import java.util.HashMap;
import java.util.Map;

/**
 * @Auther: zhangpeng
 * @Date: 2020/10/29 17
 * @Description:
 */
public class test3 {
    public static void main(String[] args) {
       /* for(int i = 1, len = str1s.length; i < len; i++){
            String str = "INSERT INTO \"MEDICAL_DICT_ITEM\"(\"ITEM_ID\", \"GROUP_ID\", \"CODE\", \"VALUE\", \"IS_ORDER\", \"REMARK\", \"KIND\") VALUES ('%s3ad7a61d07471f8109c0c811bdb3cd', 'e60fdcd7b368f88a0e4f6e0745409976', '%s', '%s', '%s', NULL, NULL);";
//            System.out.println(str1s[i].toUpperCase() + "." + str2s[i].toUpperCase() + "\t" + str3[i]);
            System.out.println(String.format(str, i,str1s[i].toUpperCase() + "." +  str2s[i].toUpperCase(),str3[i], i) );
        }
        System.out.println(str1s.length);
        System.out.println(str2s.length);*/

       Map<String, String> map = new HashMap<>();
       map.put("a", "1");
       map.put("b", "2");
       HashMap map2 = JSONObject.parseObject(JSONObject.toJSONString(map), HashMap.class);
    }

    static String[] str1s = {

            "dws_order_hisitem_diff_detail",
            "dws_order_hisitem_diff_detail",
            "dws_itemprice_higher_detail",
            "dws_itemprice_higher_detail",
            "dws_itemprice_higher_detail",
            "dws_itemexchange1_diffitem",
            "dws_itemexchange1_diffitem",
            "dws_itemexchange1_diffitem",
            "dws_onebed_morepatients",
            "dws_onebed_morepatients",
            "dws_onebed_morepatients",
            "dws_onebed_morepatients",
            "dws_itemexchange2_morecharge",
            "dws_itemexchange2_morecharge",
            "dws_hischarge_noresult",
            "dws_hischarge_noresult",
            "dws_ybcharge_noresult",
            "dws_ybcharge_noresult",
            "dws_hisitemqtymoreorder_detail",
            "dws_hisitemqtymoreorder_detail",
            "dws_hisitemqtymoreorder_detail",
            "dws_hisitemqtymoreorder_detail",
            "dws_hisitemqtymoreorder_detail",
            "dws_ybitemqtymoreorder_detail",
            "dws_ybitemqtymoreorder_detail",
            "dws_ybitemqtymoreorder_detail",
            "dws_ybitemqtymoreorder_detail",
            "dws_ybitemqtymoreorder_detail",
            "dws_order_ybitem_diff_detail",
            "dws_order_ybitem_diff_detail",
            "dws_newitem_onfile_detail",
            "dws_zyapart_days",
            "dws_zyapart_days",
            "dws_zyapart_days",
            "dws_zyapart_days",
            "dws_zyapart_days",
            "dws_zyapart_days",
            "dws_clientdeath_visit_detail",
            "dws_clientdeath_visit_detail",
            "dws_testdate_leavedate",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_Rxapart_days",
            "dws_doctordeath_practice_detail",
            "dws_doctordeath_practice_detail",
            "dws_inhospital_overlap",
            "dws_inhospital_overlap",
            "dws_inhospital_overlap",
            "dws_inhospital_overlap",
            "dws_inhospital_overlap",
            "dws_inhospital_overlap",
            "dws_clinic_inhospital",
            "dws_clinic_inhospital",
            "dws_clinic_inhospital",
            "dws_clinic_inhospital",
    };
    static String[] str2s = {

            "item_qty",
            "chargeunit",
            "itemprice_detail",
            "itemprice_fixing",
            "item_qty",
            "his_itemname",
            "his_itemname_src",
            "yb_item_qty",
            "openbeds",
            "duration",
            "in_patient_qty",
            "violationvisit_cnt",
            "falseitem_qty_yb",
            "falseitem_qty_his",
            "item_qty",
            "chargeunit",
            "item_qty",
            "chargeunit",
            "itemname_src_order",
            "itemname_charge_src_order",
            "item_qty_order",
            "item_qty_hischarge",
            "chargeunit",
            "itemname_src_order",
            "itemname_charge_src_order",
            "item_qty_order",
            "item_qty_ybcharge",
            "chargeunit",
            "item_qty",
            "chargeunit",
            "newitem_qty",
            "deptname_this",
            "zy_id_last",
            "orgname_last",
            "deptname_last",
            "zy_apart_days",
            "diseasename_last",
            "deathdate",
            "visitdate",
            "test_date",
            "deptname",
            "doctorname",
            "prescriptno_this",
            "prescripttime_this",
            "prescriptno_last",
            "prescripttime_last",
            "Rx_apart_minute",
            "doctorname",
            "deathdate",
            "zy_id_one",
            "admitdate_one",
            "leavedate_one",
            "orgname_one",
            "deptname_one",
            "deptname_other",
            "zy_id_this",
            "admitdate_this",
            "leavedate_this",
            "deptname_clinic",
    };

    static String[] str3 = {
            "违规项目数量",
            "销售单位",
            "项目单价",
            "官方限定价格",
            "违规项目数量",
            "违规项目_医院",
            "违规项目_医院（原始）",
            "违规项目数量",
            "科室开放床位数",
            "叠床发生日期",
            "当天在院患者人数",
            "违规人次",
            "项目数量_医保",
            "项目数量_医院",
            "违规项目数量",
            "销售单位",
            "违规项目数量",
            "销售单位",
            "医嘱项目名称（原始）",
            "医嘱对应的收费项目名称（原始）",
            "医嘱项目数量",
            "违规项目数量",
            "销售单位",
            "医嘱项目名称（原始）",
            "医嘱对应的收费项目名称（原始）",
            "医嘱项目数量",
            "违规项目数量",
            "销售单位",
            "违规项目数量",
            "销售单位",
            "违规项目数量",
            "科室名称（原始）",
            "上次就诊ID",
            "上次就诊医疗机构名称",
            "上次就诊科室名称",
            "两次住院间隔天数",
            "上次疾病诊断名称",
            "患者死亡日期",
            "死亡后就诊日期",
            "化验日期",
            "科室名称（原始）",
            "医师姓名",
            "处方号",
            "处方时间",
            "上次处方号",
            "上次处方时间",
            "处方时间间隔",
            "医师姓名",
            "医师死亡时间",
            "前就诊ID",
            "前就诊日期",
            "前出院时间",
            "前医疗机构名称",
            "前科室名称（原始）",
            "科室名称（原始）",
            "住院就诊ID",
            "入院日期",
            "出院日期",
            "科室名称（原始）",
    };
}
